spring:
  datasource:
    url: jdbc:sqlserver://springpoc.database.windows.net:1433;database=springpoc;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: springpoc
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080
  